version: "3.9"

services:
  app:
    build: .
    image: chsm_serv:latest
    container_name: chsm_serv
    restart: unless-stopped
    ports:
      - "5008:5001"
    env_file:
      - .env
    environment:
      - PORT=5001
      - NODE_ENV=production