name: Bun CI/CD with Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: "chsm_serv"
  DEPLOY_DIR: "/root/chsm_serv"
  CONTAINER_NAME: "chsm_serv"
  HOST_PORT: "5008"
  CONTAINER_PORT: "5001" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Шаг 4: Сборка проекта
      - name: Build project
        run: bun run build

      # Шаг 5: Сборка Docker-образа
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          # Используем --file Dockerfile на случай, если их несколько
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker images

      - name: Save Docker image
        run: |
          docker save ${{ env.DOCKER_IMAGE }} -o ${{ env.DOCKER_IMAGE }}.tar

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy files to remote server
        run: |
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p ${{ env.DEPLOY_DIR }}"
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" scp -o StrictHostKeyChecking=no ${{ env.DOCKER_IMAGE }}.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ env.DEPLOY_DIR }}/
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ env.DEPLOY_DIR }}/

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy Docker image on remote server
        run: |
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ${{ env.DEPLOY_DIR }} &&
            docker load -i ${{ env.DOCKER_IMAGE }}.tar &&
            mkdir -p data && chmod 777 data &&
            docker-compose down || true
            docker-compose up -d &&
            rm ${{ env.DOCKER_IMAGE }}.tar &&
            docker image prune -f
          "